package com.example.composethemestest.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

data class ExtendedColors(
    val material: ColorScheme,
    val surfaceTint: Color,
    val shadow: Color,
    val warning: Color,
    val onWarning: Color,
    val warningContainer: Color,
    val onWarningContainer: Color,
    val success: Color,
    val onSuccess: Color,
    val successContainer: Color,
    val onSuccessContainer: Color,
    val ai: Color,
    val onAi: Color,
    val aiContainer: Color,
    val onAiContainer: Color,
)

val lightColors = ExtendedColors(
    material = lightColorScheme(
        primary = UnifiedColors.BaseIndigo_120,
        onPrimary = UnifiedColors.BaseIndigo_250,
        primaryContainer = UnifiedColors.BaseIndigo_220,
        onPrimaryContainer = UnifiedColors.BaseIndigo_100,
        secondary = UnifiedColors.BaseIndigo_140,
        onSecondary = UnifiedColors.BaseIndigo_250,
        secondaryContainer = UnifiedColors.BaseIndigo_230,
        onSecondaryContainer = UnifiedColors.BaseIndigo_80,
        tertiary = UnifiedColors.BaseIndigo_160,
        onTertiary = UnifiedColors.BaseIndigo_250,
        tertiaryContainer = UnifiedColors.BaseIndigo_240,
        onTertiaryContainer = UnifiedColors.BaseIndigo_60,
        error = UnifiedColors.BaseRed_140,
        onError = UnifiedColors.BaseRed_250,
        errorContainer = UnifiedColors.BaseRed_230,
        onErrorContainer = UnifiedColors.BaseRed_110,
        background = UnifiedColors.BaseGray_250,
        onBackground = UnifiedColors.BaseGray_50,
        surface = UnifiedColors.BaseGray_240,
        onSurface = UnifiedColors.BaseGray_50,
        surfaceVariant = UnifiedColors.BaseGray_235,
        onSurfaceVariant = UnifiedColors.BaseGray_100,
        outline = UnifiedColors.BaseGray_140,
        outlineVariant = UnifiedColors.BaseGray_210,
        scrim = UnifiedColors.BaseGray_0,
        inverseSurface = UnifiedColors.BaseGray_50,
        inverseOnSurface = UnifiedColors.BaseGray_245,
        inversePrimary = UnifiedColors.BaseIndigo_210,
        surfaceDim = UnifiedColors.BaseGray_220,
        surfaceBright = UnifiedColors.BaseGray_250,
        surfaceContainerLowest = UnifiedColors.BaseGray_250,
        surfaceContainerLow = UnifiedColors.BaseGray_250,
        surfaceContainer = UnifiedColors.BaseGray_245,
        surfaceContainerHigh = UnifiedColors.BaseGray_250,
        surfaceContainerHighest = UnifiedColors.BaseGray_250,
    ),
    surfaceTint = UnifiedColors.BaseIndigo_160,
    shadow = UnifiedColors.BaseGray_0,
    warning = UnifiedColors.BaseOrange_170,
    onWarning = UnifiedColors.BaseGray_250,
    warningContainer = UnifiedColors.BaseOrange_230,
    onWarningContainer = UnifiedColors.BaseOrange_100,
    success = UnifiedColors.BaseGreen_140,
    onSuccess = UnifiedColors.BaseGray_250,
    successContainer = UnifiedColors.BaseGreen_240,
    onSuccessContainer = UnifiedColors.BaseGreen_100,
    ai = UnifiedColors.BasePurple_140,
    onAi = UnifiedColors.BaseGray_250,
    aiContainer = UnifiedColors.BasePurple_230,
    onAiContainer = UnifiedColors.BasePurple_100,
)

val darkColors = ExtendedColors(
    material = darkColorScheme(
        primary = UnifiedColors.BaseIndigo_180,
        onPrimary = UnifiedColors.BaseIndigo_60,
        primaryContainer = UnifiedColors.BaseGray_90,
        onPrimaryContainer = UnifiedColors.BaseIndigo_190,
        secondary = UnifiedColors.BaseIndigo_170,
        onSecondary = UnifiedColors.BaseIndigo_50,
        secondaryContainer = UnifiedColors.BaseGray_80,
        onSecondaryContainer = UnifiedColors.BaseIndigo_180,
        tertiary = UnifiedColors.BaseIndigo_160,
        onTertiary = UnifiedColors.BaseIndigo_40,
        tertiaryContainer = UnifiedColors.BaseGray_70,
        onTertiaryContainer = UnifiedColors.BaseIndigo_210,
        error = UnifiedColors.BaseRed_200,
        onError = UnifiedColors.BaseRed_80,
        errorContainer = UnifiedColors.BaseRed_50,
        onErrorContainer = UnifiedColors.BaseRed_210,
        background = UnifiedColors.BaseGray_0,
        onBackground = UnifiedColors.BaseGray_240,
        surface = UnifiedColors.BaseGray_50,
        onSurface = UnifiedColors.BaseGray_240,
        surfaceVariant = UnifiedColors.BaseGray_70,
        onSurfaceVariant = UnifiedColors.BaseGray_210,
        outline = UnifiedColors.BaseGray_150,
        outlineVariant = UnifiedColors.BaseGray_100,
        scrim = UnifiedColors.BaseGray_0,
        inverseSurface = UnifiedColors.BaseGray_245,
        inverseOnSurface = UnifiedColors.BaseGray_50,
        inversePrimary = UnifiedColors.BaseIndigo_120,
        surfaceDim = UnifiedColors.BaseGray_0,
        surfaceBright = UnifiedColors.BaseGray_80,
        surfaceContainerLowest = UnifiedColors.BaseGray_0,
        surfaceContainerLow = UnifiedColors.BaseGray_50,
        surfaceContainer = UnifiedColors.BaseGray_60,
        surfaceContainerHigh = UnifiedColors.BaseGray_65,
        surfaceContainerHighest = UnifiedColors.BaseGray_70,
    ),
    surfaceTint = UnifiedColors.BaseIndigo_80,
    shadow = UnifiedColors.BaseGray_0,
    warning = UnifiedColors.BaseOrange_200,
    onWarning = UnifiedColors.BaseOrange_80,
    warningContainer = UnifiedColors.BaseOrange_80,
    onWarningContainer = UnifiedColors.BaseOrange_230,
    success = UnifiedColors.BaseGreen_200,
    onSuccess = UnifiedColors.BaseGreen_80,
    successContainer = UnifiedColors.BaseGreen_80,
    onSuccessContainer = UnifiedColors.BaseGreen_230,
    ai = UnifiedColors.BasePurple_200,
    onAi = UnifiedColors.BasePurple_80,
    aiContainer = UnifiedColors.BasePurple_80,
    onAiContainer = UnifiedColors.BasePurple_230,
)





